# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Build all branches except for tags
trigger:
  branches:
    include:
    - '*'
    exclude:
    - 'refs/tags/*'

jobs:
- job: Setup
  displayName: Setup a docker container
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - bash: |
      echo $(DockerPassword) | docker login -u $(DockerUserName) --password-stdin
      docker build -t lightmetrica-v3-azure .
      docker images
      docker tag lightmetrica-v3-travis $(DockerUserName)/lightmetrica-v3-azure
      docker push $(DockerUserName)/lightmetrica-v3-azure
