FROM jupyter/scipy-notebook
MAINTAINER Hisanari Otsu <hi2p.perim@gmail.com>

ENV BUILD_CORES -j
USER root

# -----------------------------------------------------------------------------

# Install some packages
RUN apt-get update -qq && apt-get install -qq -y \
    git \
    software-properties-common \
    build-essential \
    wget \
    unzip \
    curl

# -----------------------------------------------------------------------------

# Update to the latest gcc
RUN add-apt-repository ppa:ubuntu-toolchain-r/test
RUN apt-get update -qq && apt-get install -y gcc-8 g++-8
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 60 --slave /usr/bin/g++ g++ /usr/bin/g++-8

# -----------------------------------------------------------------------------

# Install cmake
WORKDIR /root
RUN curl -OL https://github.com/Kitware/CMake/releases/download/v3.13.1/cmake-3.13.1-Linux-x86_64.sh
RUN sh cmake-3.13.1-Linux-x86_64.sh --skip-license --prefix=/usr/local/

# -----------------------------------------------------------------------------

# Install dependencies
# pybind11
WORKDIR /root
RUN git clone --depth 1 https://github.com/pybind/pybind11.git
WORKDIR /root/pybind11
RUN cmake -H. -B_build -DCMAKE_BUILD_TYPE=Release -DPYBIND11_TEST=OFF && \
    cmake --build _build --target install

# json
WORKDIR /root
RUN git clone --depth 1 https://github.com/nlohmann/json.git
WORKDIR /root/json
RUN cmake -H. -B_build -DCMAKE_BUILD_TYPE=Release -DJSON_BuildTests=OFF && \
    cmake --build _build --target install

# glm
WORKDIR /root
RUN git clone --depth 1 https://github.com/g-truc/glm.git
WORKDIR /root/glm
RUN cmake -H. -B_build -DCMAKE_BUILD_TYPE=Release -DGLM_TEST_ENABLE=OFF && \
    cmake --build _build --target install

# doctest
WORKDIR /root
RUN git clone --depth 1 https://github.com/onqtam/doctest.git
WORKDIR /root/doctest
RUN cmake -H. -B_build -DCMAKE_BUILD_TYPE=Release -DDOCTEST_WITH_TESTS=OFF && \
    cmake --build _build --target install

# fmt
WORKDIR /root
RUN git clone --depth 1 https://github.com/fmtlib/fmt.git
WORKDIR /root/fmt
RUN cmake -H. -B_build -DCMAKE_BUILD_TYPE=Release -DFMT_DOC=OFF -DFMT_TEST=OFF && \
    cmake --build _build --target install

# cereal
WORKDIR /root
RUN git clone --depth 1 https://github.com/USCiLab/cereal.git
WORKDIR /root/cereal
RUN cmake -H. -B_build -DCMAKE_BUILD_TYPE=Release -DJUST_INSTALL_CEREAL=ON && \
    cmake --build _build --target install

# rang
WORKDIR /root
RUN git clone --depth 1 https://github.com/agauniyal/rang.git
WORKDIR /root/rang
RUN cmake -H. -B_build -DCMAKE_BUILD_TYPE=Release && \
    cmake --build _build --target install

# -----------------------------------------------------------------------------

WORKDIR /home/$NB_USER/work
USER $NB_USER
