name: lm3_dev
channels:
  - conda-forge
dependencies:
  - python=3.7
  - cmake
  - jupyter
  - matplotlib
  - scipy
  - pandas
  - sphinx
  - sphinx_rtd_theme
  - jupytext
  - tqdm
  - colorama
  - imageio
  - pytest
  - pybind11
  - embree3
  - glm
  # Temporarily downgraded
  - nlohmann_json=3.10.2
  - glew
  - tbb-devel
  - doctest
  - fmt
  - hi2p-perim::stb
  - hi2p-perim::cereal
  - hi2p-perim::vdbloader
  - hi2p-perim::pbrt-parser
  - pip:
    - sphinx-autobuild
    - breathe
    - sphinx_tabs
    - nbsphinx
    - nbmerge