/*
    Lightmetrica - Copyright (c) 2018 Hisanari Otsu
    Distributed under MIT license. See LICENSE file for details.
*/

#pragma once

#include "detail/component.h"

LM_NAMESPACE_BEGIN(LM_NAMESPACE)

/*!
    \brief 3D model format.
    Aggregates multiple meshes and materials generated by the model.
*/
class Model : public Component {
public:
    /*!
        \brief Create primitives from underlying components.
    */
    using CreatePrimitiveFunc = std::function<void(Component* mesh, Component* material)>;
    virtual void createPrimitives(const CreatePrimitiveFunc& createPrimitive) const = 0;
};

LM_NAMESPACE_END(LM_NAMESPACE)
